source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.5"

gem "rails", "~> 7.0.10"

gem "puma", ">= 5.0"
gem 'mongoid', '~> 7.3'
gem 'twilio-ruby'
gem 'rack-cors'
gem 'devise'
gem 'devise-jwt'
gem 'jsonapi-serializer'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

group :development, :test do
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
